import {
  Award,
  Building2,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CloudSun,
  CodeXml,
  Contact,
  Database,
  ExternalLink,
  FolderCode,
  GraduationCap,
  Home,
  Languages,
  Mail,
  Moon,
  Presentation,
  Route,
  Server,
  ShieldCheck,
  Smartphone,
  Sun,
  X,
} from 'lucide-react'

const icons = {
  award: Award,
  building: Building2,
  calendar: CalendarDays,
  chevron: ChevronDown,
  cloud: CloudSun,
  code: CodeXml,
  contact: Contact,
  database: Database,
  external: ExternalLink,
  folder: FolderCode,
  github: CodeXml,
  graduation: GraduationCap,
  home: Home,
  languages: Languages,
  left: ChevronLeft,
  linkedin: Contact,
  mail: Mail,
  moon: Moon,
  presentation: Presentation,
  route: Route,
  right: ChevronRight,
  server: Server,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sun: Sun,
  x: X,
}

export function Icon({ name, size = 20, className = '', ...props }) {
  const Component = icons[name] ?? CodeXml
  const classes = ['fluent-icon', className].filter(Boolean).join(' ')
  return <Component aria-hidden="true" className={classes} size={size} strokeWidth={2} {...props} />
}
